name: cmb-forecast
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.12
  - pip
  - pip:
      - jax
      - numpy
      - scipy
      - pytest
      - camb  # only needed to regenerate data/ templates via generate_camb_templates.py
      - jupyterlab
      - ipykernel
